"""rename_doi_to_isbn

Revision ID: 0aae9791edae
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 15:45:41.392460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aae9791edae'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_abstracts', sa.Column('isbn', sa.String(length=100), nullable=True))
    op.drop_column('publication_abstracts', 'doi')
    op.add_column('publication_books', sa.Column('isbn', sa.String(length=100), nullable=True))
    op.drop_column('publication_books', 'doi')
    op.add_column('publication_collection_articles', sa.Column('isbn', sa.String(length=100), nullable=True))
    op.drop_column('publication_collection_articles', 'doi')
    op.add_column('publication_dissertations', sa.Column('isbn', sa.String(length=100), nullable=True))
    op.drop_column('publication_dissertations', 'doi')
    op.add_column('publication_internets', sa.Column('isbn', sa.String(length=100), nullable=True))
    op.drop_column('publication_internets', 'doi')
    op.add_column('publication_journal_articles', sa.Column('isbn', sa.String(length=100), nullable=True))
    op.drop_column('publication_journal_articles', 'doi')
    op.add_column('publication_newspaper_articles', sa.Column('isbn', sa.String(length=100), nullable=True))
    op.drop_column('publication_newspaper_articles', 'doi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_newspaper_articles', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_newspaper_articles', 'isbn')
    op.add_column('publication_journal_articles', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_journal_articles', 'isbn')
    op.add_column('publication_internets', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_internets', 'isbn')
    op.add_column('publication_dissertations', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_dissertations', 'isbn')
    op.add_column('publication_collection_articles', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_collection_articles', 'isbn')
    op.add_column('publication_books', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_books', 'isbn')
    op.add_column('publication_abstracts', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_abstracts', 'isbn')
    # ### end Alembic commands ###
