"""rename_doi_to_isbn

Revision ID: 0aae9791edae
Revises: a1b2c3d4e5f6
Create Date: 2026-05-14 15:45:41.392460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '0aae9791edae'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table: str, column: str) -> bool:
    conn = op.get_bind()
    return any(c['name'] == column for c in inspect(conn).get_columns(table))


def upgrade() -> None:
    """Upgrade schema."""
    tables = [
        'publication_abstracts',
        'publication_books',
        'publication_collection_articles',
        'publication_dissertations',
        'publication_internets',
        'publication_journal_articles',
        'publication_newspaper_articles',
    ]
    for table in tables:
        conn = op.get_bind()
        if table not in inspect(conn).get_table_names():
            continue
        if not _column_exists(table, 'isbn'):
            op.add_column(table, sa.Column('isbn', sa.String(length=100), nullable=True))
        if _column_exists(table, 'doi'):
            op.drop_column(table, 'doi')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_newspaper_articles', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_newspaper_articles', 'isbn')
    op.add_column('publication_journal_articles', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_journal_articles', 'isbn')
    op.add_column('publication_internets', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_internets', 'isbn')
    op.add_column('publication_dissertations', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_dissertations', 'isbn')
    op.add_column('publication_collection_articles', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_collection_articles', 'isbn')
    op.add_column('publication_books', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_books', 'isbn')
    op.add_column('publication_abstracts', sa.Column('doi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('publication_abstracts', 'isbn')
    # ### end Alembic commands ###
