"""add creator_id to announcements and create announcement_views table

Revision ID: 1b6f4e059876
Revises: 95907b770301
Create Date: 2026-05-06 13:16:32.560141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6f4e059876'
down_revision: Union[str, Sequence[str], None] = '95907b770301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_announcement_user_view')
    )
    op.add_column('announcements', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'announcements', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'creator_id')
    op.drop_table('announcement_views')
    # ### end Alembic commands ###
