"""add_scopus_vak_to_journal_articles

Revision ID: 1c2eea697955
Revises: 0aae9791edae
Create Date: 2026-05-14 16:05:21.444958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '1c2eea697955'
down_revision: Union[str, Sequence[str], None] = '0aae9791edae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    columns = [c['name'] for c in inspect(conn).get_columns('publication_journal_articles')]
    if 'scopus' not in columns:
        op.add_column('publication_journal_articles', sa.Column('scopus', sa.Boolean(), nullable=True))
    if 'vak' not in columns:
        op.add_column('publication_journal_articles', sa.Column('vak', sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_journal_articles', 'vak')
    op.drop_column('publication_journal_articles', 'scopus')
    # ### end Alembic commands ###
