"""empty message

Revision ID: 33970fece893
Revises: ec95d1f5ce20
Create Date: 2026-05-04 21:12:26.192212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33970fece893'
down_revision: Union[str, Sequence[str], None] = 'ec95d1f5ce20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_user_assignments', sa.Column('marked_complete', sa.Boolean(), nullable=True))
    op.add_column('task_user_assignments', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('task_user_assignments', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task_user_assignments', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('no_review', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('academic_title', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('degree', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('rate_type', sa.String(length=50), server_default='основная', nullable=False))
    op.add_column('users', sa.Column('rate_count', sa.Float(), server_default=sa.text('1.0'), nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'rate_count')
    op.drop_column('users', 'rate_type')
    op.drop_column('users', 'degree')
    op.drop_column('users', 'academic_title')
    op.drop_column('users', 'phone')
    op.drop_column('tasks', 'no_review')
    op.drop_column('task_user_assignments', 'approved_at')
    op.drop_column('task_user_assignments', 'completed_at')
    op.drop_column('task_user_assignments', 'approved')
    op.drop_column('task_user_assignments', 'marked_complete')
    # ### end Alembic commands ###
