"""add cascade delete on task_user_assignments fk

Revision ID: 3ea0cd686485
Revises: 94eaf2fef4b8
Create Date: 2026-05-10 15:56:43.793644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea0cd686485'
down_revision: Union[str, Sequence[str], None] = '94eaf2fef4b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('task_user_assignments_task_id_fkey'), 'task_user_assignments', type_='foreignkey')
    op.drop_constraint(op.f('task_user_assignments_user_id_fkey'), 'task_user_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'task_user_assignments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_user_assignments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_user_assignments', type_='foreignkey')
    op.drop_constraint(None, 'task_user_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('task_user_assignments_user_id_fkey'), 'task_user_assignments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('task_user_assignments_task_id_fkey'), 'task_user_assignments', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
