"""remove is_personal column from tasks

Revision ID: 4068aef9fbea
Revises: d0b41a8db714
Create Date: 2026-05-06 00:19:50.465946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4068aef9fbea'
down_revision: Union[str, Sequence[str], None] = 'd0b41a8db714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_personal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_personal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
