"""remove starts_at from tasks

Revision ID: 4243ac7f3cf0
Revises: 1b6f4e059876
Create Date: 2026-05-06 14:17:16.369388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4243ac7f3cf0'
down_revision: Union[str, Sequence[str], None] = '1b6f4e059876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'starts_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('starts_at', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
