"""add chat_message_id to attachments

Revision ID: 4736ba151823
Revises: a1b2c3d4e5f6
Create Date: 2026-05-08 22:02:32.816870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4736ba151823'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('chat_message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'general_chat', ['chat_message_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'chat_message_id')
    # ### end Alembic commands ###
