"""Add meeting_id to Attachment model

Revision ID: 77f5cbb55f2c
Revises: 201e5b2f88f2
Create Date: 2026-05-06 23:11:14.463889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f5cbb55f2c'
down_revision: Union[str, Sequence[str], None] = '201e5b2f88f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('meeting_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'department_meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'meeting_id')
    # ### end Alembic commands ###
