"""replace attachment_id with document_id in documents table

Revision ID: 95907b770301
Revises: d5fdf4089f03
Create Date: 2026-05-06 10:22:04.698293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95907b770301'
down_revision: Union[str, Sequence[str], None] = 'd5fdf4089f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    
    # Migrate: set document_id on existing attachments based on documents.attachment_id
    conn = op.get_bind()
    docs = conn.execute(
        sa.text("SELECT id, attachment_id FROM documents WHERE attachment_id IS NOT NULL")
    ).fetchall()
    for doc in docs:
        conn.execute(
            sa.text("UPDATE attachments SET document_id = :doc_id WHERE id = :attach_id"),
            {"doc_id": doc[0], "attach_id": doc[1]}
        )
    
    op.drop_constraint(op.f('documents_attachment_id_fkey'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'attachment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('attachment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('documents_attachment_id_fkey'), 'documents', 'attachments', ['attachment_id'], ['id'])
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'document_id')
    # ### end Alembic commands ###
