"""add student_report to publication tables

Revision ID: af898da64219
Revises: 1c2eea697955
Create Date: 2026-05-14 16:41:55.688541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'af898da64219'
down_revision: Union[str, Sequence[str], None] = '1c2eea697955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    tables = [
        'publication_abstracts',
        'publication_books',
        'publication_collection_articles',
        'publication_dissertations',
        'publication_internets',
        'publication_journal_articles',
        'publication_newspaper_articles',
    ]
    for table in tables:
        conn = op.get_bind()
        if table not in inspect(conn).get_table_names():
            continue
        columns = [c['name'] for c in inspect(conn).get_columns(table)]
        if 'student_report' not in columns:
            op.add_column(table, sa.Column('student_report', sa.Boolean(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_newspaper_articles', 'student_report')
    op.drop_column('publication_journal_articles', 'student_report')
    op.drop_column('publication_internets', 'student_report')
    op.drop_column('publication_dissertations', 'student_report')
    op.drop_column('publication_collection_articles', 'student_report')
    op.drop_column('publication_books', 'student_report')
    op.drop_column('publication_abstracts', 'student_report')
    # ### end Alembic commands ###
