"""add student_report to publication tables

Revision ID: af898da64219
Revises: 1c2eea697955
Create Date: 2026-05-14 16:41:55.688541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af898da64219'
down_revision: Union[str, Sequence[str], None] = '1c2eea697955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication_abstracts', sa.Column('student_report', sa.Boolean(), nullable=True))
    op.add_column('publication_books', sa.Column('student_report', sa.Boolean(), nullable=True))
    op.add_column('publication_collection_articles', sa.Column('student_report', sa.Boolean(), nullable=True))
    op.add_column('publication_dissertations', sa.Column('student_report', sa.Boolean(), nullable=True))
    op.add_column('publication_internets', sa.Column('student_report', sa.Boolean(), nullable=True))
    op.add_column('publication_journal_articles', sa.Column('student_report', sa.Boolean(), nullable=True))
    op.add_column('publication_newspaper_articles', sa.Column('student_report', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_newspaper_articles', 'student_report')
    op.drop_column('publication_journal_articles', 'student_report')
    op.drop_column('publication_internets', 'student_report')
    op.drop_column('publication_dissertations', 'student_report')
    op.drop_column('publication_collection_articles', 'student_report')
    op.drop_column('publication_books', 'student_report')
    op.drop_column('publication_abstracts', 'student_report')
    # ### end Alembic commands ###
