"""add_entity_coauthors_remove_rating_template_users

Revision ID: b5afe9b60f32
Revises: 76e98acda964
Create Date: 2026-05-10 19:44:05.078780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5afe9b60f32'
down_revision: Union[str, Sequence[str], None] = '76e98acda964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_coauthors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'user_id', name='uq_entity_coauthor')
    )
    op.drop_table('rating_template_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_template_users',
    sa.Column('rating_template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rating_template_id'], ['rating_templates.id'], name=op.f('rating_template_users_rating_template_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('rating_template_users_user_id_fkey')),
    sa.PrimaryKeyConstraint('rating_template_id', 'user_id', name=op.f('rating_template_users_pkey'))
    )
    op.drop_table('entity_coauthors')
    # ### end Alembic commands ###
