"""remove TaskGroup model and task_groups table

Revision ID: cd9d20ab866e
Revises: 33970fece893
Create Date: 2026-05-05 23:04:48.046094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9d20ab866e'
down_revision: Union[str, Sequence[str], None] = '33970fece893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_groups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_groups',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('task_groups_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('task_groups_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'group_id', name=op.f('task_groups_pkey'))
    )
    # ### end Alembic commands ###
