"""refactor document model to use attachment table

Revision ID: d0b41a8db714
Revises: cd9d20ab866e
Create Date: 2026-05-05 23:41:07.406958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0b41a8db714'
down_revision: Union[str, Sequence[str], None] = 'cd9d20ab866e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('documents', sa.Column('attachment_id', sa.Integer(), nullable=True))
    # Migrate existing documents: create attachments for documents with filepath/filename
    conn = op.get_bind()
    documents = conn.execute(
        sa.text("SELECT id, filename, filepath FROM documents WHERE filepath IS NOT NULL AND filepath != ''")
    ).fetchall()
    for doc in documents:
        conn.execute(
            sa.text("INSERT INTO attachments (task_id, file_name, file_path, mime_type, size, uploaded_at) VALUES (NULL, :filename, :filepath, 'application/octet-stream', 0, NOW())"),
            {"filename": doc[1] or "unknown", "filepath": doc[2]}
        )
        attachment_id = conn.execute(sa.text("SELECT lastval()")).scalar()
        conn.execute(
            sa.text("UPDATE documents SET attachment_id = :aid WHERE id = :id"),
            {"aid": attachment_id, "id": doc[0]}
        )
    op.alter_column('documents', 'attachment_id', nullable=False)
    op.create_foreign_key(None, 'documents', 'attachments', ['attachment_id'], ['id'])
    op.drop_column('documents', 'filename')
    op.drop_column('documents', 'filepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('filepath', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('documents', sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'attachment_id')
    op.alter_column('attachments', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
