"""add news_id and announcement_id to attachments

Revision ID: d5fdf4089f03
Revises: 4068aef9fbea
Create Date: 2026-05-06 10:10:48.081358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fdf4089f03'
down_revision: Union[str, Sequence[str], None] = '4068aef9fbea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('news_id', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('announcement_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'attachments', 'announcements', ['announcement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'attachments', 'news', ['news_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.drop_column('attachments', 'announcement_id')
    op.drop_column('attachments', 'news_id')
    # ### end Alembic commands ###
