"""remove newspaper_article, rename collection_article, add book_type to book

Revision ID: e867f887a2d5
Revises: af898da64219
Create Date: 2026-05-14 16:53:42.139594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e867f887a2d5'
down_revision: Union[str, Sequence[str], None] = 'af898da64219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_index(table: str, index_name: str) -> bool:
    conn = op.get_bind()
    return any(idx['name'] == index_name for idx in inspect(conn).get_indexes(table))


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    tables = inspect(conn).get_table_names()
    if 'publication_newspaper_articles' in tables:
        if _has_index('publication_newspaper_articles', 'ix_publication_newspaper_articles_user_id'):
            op.drop_index(op.f('ix_publication_newspaper_articles_user_id'), table_name='publication_newspaper_articles')
        op.drop_table('publication_newspaper_articles')
    columns = [c['name'] for c in inspect(conn).get_columns('publication_books')]
    if 'book_type' not in columns:
        op.add_column('publication_books', sa.Column('book_type', sa.String(length=50), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication_books', 'book_type')
    op.create_table('publication_newspaper_articles',
    sa.Column('authors', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('newspaper_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('newspaper_date', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('issue', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('gost_string', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('student_report', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('publication_newspaper_articles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('publication_newspaper_articles_pkey'))
    )
    op.create_index(op.f('ix_publication_newspaper_articles_user_id'), 'publication_newspaper_articles', ['user_id'], unique=False)
    # ### end Alembic commands ###
