"""Remove meeting_announcements and meeting_documents tables

Revision ID: e958c3f1e943
Revises: 77f5cbb55f2c
Create Date: 2026-05-06 23:18:58.296869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e958c3f1e943'
down_revision: Union[str, Sequence[str], None] = '77f5cbb55f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_documents')
    op.drop_table('meeting_announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_announcements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('announcement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], name=op.f('meeting_announcements_announcement_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['department_meetings.id'], name=op.f('meeting_announcements_meeting_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_announcements_pkey')),
    sa.UniqueConstraint('meeting_id', 'announcement_id', name=op.f('uq_meeting_announcement'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('meeting_documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('meeting_documents_document_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['department_meetings.id'], name=op.f('meeting_documents_meeting_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_documents_pkey')),
    sa.UniqueConstraint('meeting_id', 'document_id', name=op.f('uq_meeting_document'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
